### ISSUE TITLE
Chat Message Context Menu Not Showing

### ISSUE THREAD

**Issue by clickxiv** [BernhardPosselt/pf2e-kingmaker-tools#14] opened 2023-03-19 01:28 UTC
With this module installed (and just this module activated), right-clicking on a message in chat no longer brings up the context menu (i.e. for rerolling or showing hidden messages to players).

**Comment by clickxiv** [comment] 2023-03-19 01:35
Here is the error message that appears in the log when I try: 
![image](https://user-images.githubusercontent.com/60618333/226148968-bba0fe5b-2ec2-425c-ad94-428f545bf31c.png)

**Comment by BernhardPosselt** [comment] 2023-03-19 10:55
That's caused by having an actor named Kingdom Sheet that hasn't been imported using the view kingdom macro

**Comment by BernhardPosselt** [comment] 2023-03-19 11:26
Added a warning on game init in the latest release, please reopen this issue if you this issue was not resolved by deleting the offending actor.

**Closed by BernhardPosselt** 2023-03-19 11:26 UTC
